{
 "title": "PhoneHome",
 "time": { "from": "now-6M", "to": "now" },
 "panels": [
  { "title": "General Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Welcome!",
   "type": "text",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 1 },
   "options": {
    "content": "# PhoneHome service\n\nThe PhoneHome service provides a insight on how many NethServer/NethSecurity installations are live and working.\nAdditional info can be found below separated by product and version."
   }
  },
  {
   "title": "Active Installations",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  day,\n  active_count AS active_firewalls\nFROM\n  phonehome_daily_active_counts\nWHERE\n  category = 'nethsecurity'\nORDER BY\n  day;"
    },
    {
     "rawSql": "SELECT\n  day,\n  active_count AS active_clusters\nFROM\n  phonehome_daily_active_counts\nWHERE\n  category = 'nethserver8'\nORDER BY\n  day;"
    },
    {
     "rawSql": "SELECT\n  day,\n  active_count AS installation_count\nFROM\n  phonehome_daily_active_counts\nWHERE\n  category = 'nethserver67'\nORDER BY\n  day;"
    }
   ]
  },
  {
   "title": "Total Installations",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*)\nFROM phonehome_installations;"
    }
   ]
  },
  { "title": "NethServer 8", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Active Nethserver 8 clusters",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*) as ns_installations\nFROM\n  phonehome_installations\nWHERE\n  category = 'nethserver8';"
    }
   ]
  },
  {
   "title": "Active Nethserver 8 installations",
   "type": "geomap",
   "gridPos": { "h": 15, "w": 10, "x": 7, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\n  country_code AS code,\n  country_name AS name,\n  COUNT(*) as old_installations\nFROM\n  phonehome_installations\nWHERE\n  category = 'nethserver8'\nGROUP BY\n  country_code,\n  country_name;"
    }
   ]
  },
  {
   "title": "Nethserver 8 node count for each cluster",
   "type": "barchart",
   "gridPos": { "h": 15, "w": 7, "x": 17, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT node_count, COUNT(*)\nFROM phonehome_installations\nWHERE category = 'nethserver8'\nGROUP BY node_count\nORDER BY node_count;"
    }
   ]
  },
  {
   "title": "Active Nethserver 8 node versions",
   "type": "table",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\n  country_name as name,\n  version,\n  COUNT(*) as old_installations\nFROM\n  phonehome_nethserver8_node_versions\nGROUP BY\n  country_name,\n  version\nORDER BY old_installations DESC, version, name;"
    }
   ]
  },
  { "title": "NethSecurity 8", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Active Nethsecurity 8 installations",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*) as nsec_installations\nFROM\n  phonehome_installations\nWHERE\n  category = 'nethsecurity';"
    }
   ]
  },
  {
   "title": "Active Nethsecurity 8 installations",
   "type": "geomap",
   "gridPos": { "h": 15, "w": 10, "x": 7, "y": 28 },
   "targets": [
    {
     "rawSql": "SELECT\n  country_code AS code,\n  country_name AS name,\n  COUNT(*) as nsec_installations\nFROM\n  phonehome_installations\nWHERE\n  category = 'nethsecurity'\nGROUP BY\n  country_code,\n  country_name;"
    }
   ]
  },
  {
   "title": "Active Nethsecurity 8 versions",
   "type": "table",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 33 },
   "targets": [
    {
     "rawSql": "SELECT country_name as name, version, COUNT(*) as installation_count\nFROM phonehome_installations\nWHERE category = 'nethsecurity'\nGROUP BY country_name, version\nORDER BY installation_count DESC, version, name;"
    }
   ]
  },
  { "title": "NethServer 6/7", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Active legacy versions",
   "type": "table",
   "gridPos": { "h": 15, "w": 7, "x": 0, "y": 44 },
   "targets": [
    {
     "rawSql": "SELECT\n  country_name as name,\n  version,\n  COUNT(*) as old_installations\nFROM\n  phonehome_installations\nWHERE\n  category = 'nethserver67'\nGROUP BY\n  country_name,\n  version\nORDER BY old_installations DESC, version, name;"
    }
   ]
  },
  {
   "title": "Active legacy installations",
   "type": "geomap",
   "gridPos": { "h": 15, "w": 10, "x": 7, "y": 44 },
   "targets": [
    {
     "rawSql": "SELECT\n  country_code AS code,\n  country_name AS name,\n  COUNT(*) as old_installations\nFROM\n  phonehome_installations\nWHERE\n  category = 'nethserver67'\nGROUP BY\n  country_code,\n  country_name;"
    }
   ]
  }
 ]
}