#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import sys
import json
import agent

request = json.load(sys.stdin)

original_environment = request['environment']

for evar in [
        'APP_DEBUG',
        'APP_URL',
        'APP_DOMAIN',
        'LOG_LEVEL',
        'GEOIP_TOKEN',
        'TRAEFIK_HOST',
        'TRAEFIK_HTTP2HTTPS',
        'TRAEFIK_LETS_ENCRYPT'
    ]:
    agent.set_env(evar, original_environment[evar])

agent.dump_env()
