#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import os

config = json.load(open('config.json'))

response = {
    'hostname': config.get('APP_DOMAIN', ''),
    'geoip_token': config.get('GEOIP_TOKEN', ''),
    'http_to_https': config.get('HTTP_TO_HTTPS', False),
    'lets_encrypt': config.get('LETS_ENCRYPT', False)
}

json.dump(response, fp=sys.stdout)
