#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent
import secrets
import string

agent.set_env('APP_NAME', 'PhoneHome')
agent.set_env('APP_ENV', 'production')

alphabet = string.ascii_letters + string.digits
agent.set_env('APP_KEY', ''.join(secrets.choice(alphabet) for i in range(32)))

agent.set_env('LOG_CHANNEL', 'stderr')
agent.set_env('LOG_DEPRECATIONS_CHANNEL', 'stderr')

agent.set_env('DB_CONNECTION', 'pgsql')
agent.set_env('DB_HOST', 'database')
agent.set_env('DB_DATABASE', 'phonehome')
agent.set_env('DB_USERNAME', 'phonehome')
agent.set_env('DB_PASSWORD', 'phonehome')

agent.set_env('BROADCAST_DRIVER', 'redis')
agent.set_env('CACHE_DRIVER', 'redis')
agent.set_env('QUEUE_CONNECTION', 'redis')
agent.set_env('SESSION_DRIVER', 'redis')

agent.set_env('PHONEHOME_REDIS_HOST', 'redis')
agent.set_env('PHONEHOME_REDIS_PASSWORD', 'null')
