#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import os
import subprocess

app_key = subprocess.run(
    [
        'podman',
        'run',
        '--rm',
        os.environ['PHONEHOME_SERVER_APP_IMAGE'],
        'php',
        'artisan',
        'key:generate',
        '--show',
    ],
    capture_output=True,
    text=True,
    check=True
).stdout.strip()

json.dump(
    {
        'APP_KEY': app_key,
        'LOG_LEVEL': 'warning',
        'LOG_CHANNEL': 'stderr',
        'LOG_DEPRECATIONS_CHANNEL': 'stderr',
        'DB_CONNECTION': 'pgsql',
        'DB_HOST': 'database',
        'DB_PORT': 5432,
        'DB_DATABASE': 'phonehome',
        'DB_USERNAME': 'phonehome',
        'DB_PASSWORD': 'phonehome',
    },
    open('config.json', 'w')
)
