#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys

# load both data from stdin and config.json
data = json.load(sys.stdin)
config = json.load(open('config.json'))

if data.get("http_to_https") == True:
    protocol = 'https://'
else:
    protocol = 'http://'

config['APP_URL'] = protocol + data.get("hostname")
config['APP_DOMAIN'] = data.get("hostname")
config['GEOIP_TOKEN'] = data.get("geoip_token")
config['HTTP_TO_HTTPS'] = data.get("http_to_https")
config['LETS_ENCRYPT'] = data.get("lets_encrypt")

# write config.json
json.dump(config, open('config.json', 'w'))
