#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import os
import sys

import agent
import agent.tasks

# Load data from stdin
data = json.load(sys.stdin)

# Fetch default Traefik
default_traefik_id = agent.resolve_agent_id('traefik@node')
if default_traefik_id is None:
    sys.exit(2)

# Configure Traefik to route requests from hostname to phonehome web service.
response = agent.tasks.run(
    agent_id=default_traefik_id,
    action='set-route',
    data={
        'instance': os.environ['MODULE_ID'],
        'url': 'http://127.0.0.1:' + os.environ["TCP_PORT"],
        'http2https': data.get("http_to_https"),
        'lets_encrypt': data.get("lets_encrypt"),
        'host': data.get("hostname")
    },
)

# Check if Traefik configuration has been successfull
agent.assert_exp(response['exit_code'] == 0)
