#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent
import agent.tasks
import os
import sys

# Fetch default Traefik
default_traefik_id = agent.resolve_agent_id('traefik@node')
if default_traefik_id is None:
    sys.exit(2)

# Configure Traefik to route requests from hostname to phonehome web service.
response = agent.tasks.run(
    agent_id=default_traefik_id,
    action='set-route',
    data={
        'instance': os.environ['MODULE_ID'],
        'url': 'http://127.0.0.1:' + os.environ["TCP_PORT"],
        'http2https': os.environ['TRAEFIK_HTTP2HTTPS'] == 'True',
        'lets_encrypt': os.environ['TRAEFIK_LETS_ENCRYPT'] == 'True',
        'host': os.environ['TRAEFIK_HOST']
    },
)

# Check if Traefik configuration has been successfull
agent.assert_exp(response['exit_code'] == 0)
